spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect
        format_sql: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true

cors:
  allowed-origin: http://localhost:3000
